name: Test Runs

on:
  push:
    branches:
      - 'bugfix/**'
      - 'improvement/**'
      - 'feature/**'
      - 'new-algo/**'

jobs:
  test: Check if all the required functionality is implemented.
  runs-on: ubuntu-latest
  env:
    AWS_ACCOUNT_ID: {{ secrets.AWS_ACCOUNT_ID }}
    AWS_REGION_ID: {{ secrets.AWS_REGION_ID }}

  



